import React, { useState } from 'react';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { Download, Share2, Loader2, ImageIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';

interface ChatBubbleProps {
  content: string;
  sender: 'user' | 'aura';
  timestamp: Date;
  className?: string;
  imageUrl?: string;
  isGeneratingImage?: boolean;
}

export const ChatBubble: React.FC<ChatBubbleProps> = ({
  content,
  sender,
  timestamp,
  className,
  imageUrl,
  isGeneratingImage
}) => {
  const isUser = sender === 'user';
  const [imageLoaded, setImageLoaded] = useState(false);

  const handleDownload = async () => {
    if (!imageUrl) return;
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `aura-image-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success('Image downloaded! 📥');
    } catch {
      toast.error('Could not download image');
    }
  };

  const handleShare = async () => {
    if (!imageUrl) return;
    try {
      if (navigator.share) {
        await navigator.share({
          title: 'AURA Generated Image',
          text: content,
          url: imageUrl
        });
      } else {
        await navigator.clipboard.writeText(imageUrl);
        toast.success('Image link copied! 📋');
      }
    } catch {
      toast.error('Could not share image');
    }
  };

  // Check if content contains an image URL (for generated images)
  const extractedImageUrl = imageUrl || (content.match(/!\[.*?\]\((data:image\/[^)]+)\)/)?.[1]);
  const textContent = content.replace(/!\[.*?\]\(data:image\/[^)]+\)/g, '').trim();

  return (
    <div 
      className={cn(
        'flex w-full animate-slide-up',
        isUser ? 'justify-end' : 'justify-start',
        className
      )}
    >
      <div className={cn(
        'max-w-[85%] px-4 py-3 rounded-2xl',
        isUser 
          ? 'bg-aura-bubble-user text-primary-foreground rounded-br-md' 
          : 'bg-aura-bubble-ai text-aura-bubble-ai-text rounded-bl-md'
      )}>
        {/* Image Generation Loading State */}
        {isGeneratingImage && (
          <div className="flex items-center gap-2 mb-2 p-3 bg-primary/10 rounded-xl">
            <Loader2 className="w-5 h-5 animate-spin text-primary" />
            <span className="text-sm text-primary">Creating your image... ✨</span>
          </div>
        )}

        {/* Generated Image Display */}
        {extractedImageUrl && (
          <div className="mb-3 space-y-2">
            <div className="relative rounded-xl overflow-hidden bg-muted/50">
              {!imageLoaded && (
                <div className="absolute inset-0 flex items-center justify-center">
                  <ImageIcon className="w-8 h-8 text-muted-foreground animate-pulse" />
                </div>
              )}
              <img 
                src={extractedImageUrl} 
                alt="Generated by AURA"
                className={cn(
                  "w-full max-w-sm rounded-xl transition-opacity duration-300",
                  imageLoaded ? "opacity-100" : "opacity-0"
                )}
                onLoad={() => setImageLoaded(true)}
              />
            </div>
            {/* Image Actions */}
            <div className="flex gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleDownload}
                className="h-7 px-2 text-xs hover:bg-primary/20"
              >
                <Download className="w-3 h-3 mr-1" />
                Save
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleShare}
                className="h-7 px-2 text-xs hover:bg-primary/20"
              >
                <Share2 className="w-3 h-3 mr-1" />
                Share
              </Button>
            </div>
          </div>
        )}

        {/* Text Content */}
        {textContent && (
          <p className="text-sm leading-relaxed whitespace-pre-wrap">{textContent}</p>
        )}
        
        <p className={cn(
          'text-[10px] mt-1.5',
          isUser ? 'text-primary-foreground/70' : 'text-muted-foreground'
        )}>
          {format(new Date(timestamp), 'h:mm a')}
        </p>
      </div>
    </div>
  );
};
